// <auto-generated />
using System;
using Collectivites.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Collectivites.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818105758_AjouterTokenReinitialisation")]
    partial class AjouterTokenReinitialisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollectiviteUtilisateur", b =>
                {
                    b.Property<Guid>("CollectivitesAccesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateursAccesId")
                        .HasColumnType("uuid");

                    b.HasKey("CollectivitesAccesId", "UtilisateursAccesId");

                    b.HasIndex("UtilisateursAccesId");

                    b.ToTable("UtilisateurCollectivites", (string)null);
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Collectivite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeAdministratif")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Geometry>("Contour")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("TypeCollectivite")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CodeAdministratif")
                        .IsUnique();

                    b.ToTable("Collectivites");

                    b.HasDiscriminator<string>("TypeCollectivite").HasValue("Collectivite");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Historique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("EntiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Entite", "EntiteId");

                    b.ToTable("Historiques");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Indicateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectiviteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateReleve")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CollectiviteId");

                    b.ToTable("Indicateurs");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.ProjetDotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectiviteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CollectiviteId");

                    b.ToTable("ProjetsDotations");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Signalement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Geometry>("Geometrie")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<string>("TypeSignalement")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Signalements");

                    b.HasDiscriminator<string>("TypeSignalement").HasValue("Signalement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenReinitialisation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Identifiant")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Commune", b =>
                {
                    b.HasBaseType("Collectivites.Api.Models.Entities.Collectivite");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Commune");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Departement", b =>
                {
                    b.HasBaseType("Collectivites.Api.Models.Entities.Collectivite");

                    b.Property<string>("Prefecture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Departement");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Epci", b =>
                {
                    b.HasBaseType("Collectivites.Api.Models.Entities.Collectivite");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siren")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Epci");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Region", b =>
                {
                    b.HasBaseType("Collectivites.Api.Models.Entities.Collectivite");

                    b.Property<string>("ChefLieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Region");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Doleance", b =>
                {
                    b.HasBaseType("Collectivites.Api.Models.Entities.Signalement");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CollectiviteRattacheeId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroSuivi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasIndex("CollectiviteRattacheeId");

                    b.HasIndex("NumeroSuivi")
                        .IsUnique();

                    b.ToTable("Signalements", t =>
                        {
                            t.Property("Statut")
                                .HasColumnName("Doleance_Statut");
                        });

                    b.HasDiscriminator().HasValue("Doleance");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Litige", b =>
                {
                    b.HasBaseType("Collectivites.Api.Models.Entities.Signalement");

                    b.Property<Guid>("CollectiviteAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectiviteBId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Geometry>("ZoneConflit")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.HasIndex("CollectiviteBId");

                    b.HasIndex("CollectiviteAId", "CollectiviteBId");

                    b.HasDiscriminator().HasValue("Litige");
                });

            modelBuilder.Entity("CollectiviteUtilisateur", b =>
                {
                    b.HasOne("Collectivites.Api.Models.Entities.Collectivite", null)
                        .WithMany()
                        .HasForeignKey("CollectivitesAccesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collectivites.Api.Models.Entities.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursAccesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Indicateur", b =>
                {
                    b.HasOne("Collectivites.Api.Models.Entities.Collectivite", "Collectivite")
                        .WithMany("Indicateurs")
                        .HasForeignKey("CollectiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collectivite");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.ProjetDotation", b =>
                {
                    b.HasOne("Collectivites.Api.Models.Entities.Collectivite", "Collectivite")
                        .WithMany("ProjetsDotations")
                        .HasForeignKey("CollectiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collectivite");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Doleance", b =>
                {
                    b.HasOne("Collectivites.Api.Models.Entities.Collectivite", "CollectiviteRattachee")
                        .WithMany()
                        .HasForeignKey("CollectiviteRattacheeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectiviteRattachee");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Litige", b =>
                {
                    b.HasOne("Collectivites.Api.Models.Entities.Collectivite", "CollectiviteA")
                        .WithMany()
                        .HasForeignKey("CollectiviteAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Collectivites.Api.Models.Entities.Collectivite", "CollectiviteB")
                        .WithMany()
                        .HasForeignKey("CollectiviteBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectiviteA");

                    b.Navigation("CollectiviteB");
                });

            modelBuilder.Entity("Collectivites.Api.Models.Entities.Collectivite", b =>
                {
                    b.Navigation("Indicateurs");

                    b.Navigation("ProjetsDotations");
                });
#pragma warning restore 612, 618
        }
    }
}
